Repository cyberbotics/webots-cloud, pull requests merged in 2022-07, with the labels that each got.

#36 Fix delete tooltip
  httpdocs/js/webots-cloud.js
Labels: bug

#37 Add terms and privacy
  httpdocs/css/webots-cloud.css
  httpdocs/index.html
  httpdocs/js/project.js
  httpdocs/js/termsAndPrivacy.js
  httpdocs/js/user.js
  httpdocs/js/webots-cloud.js
Labels: documentation

#39 Fix if email does not exist
  httpdocs/js/user.js
Labels: bug

#40 Update terms of service and privacy policy
  httpdocs/css/webots-cloud.css
  httpdocs/js/project.js
  httpdocs/js/router.js
  httpdocs/js/termsAndPrivacy.js
  httpdocs/js/user.js
  httpdocs/js/webots-cloud.js
Labels: cleanup

#41 improve Add a project message
  httpdocs/js/webots-cloud.js
Labels: documentation

#42 Add search bar and sort by
  database/webots-cloud.sql
  httpdocs/404.php
  httpdocs/ajax/animation/list.php
  httpdocs/ajax/project/create.php
  httpdocs/ajax/project/list.php
  httpdocs/css/webots-cloud.css
  httpdocs/js/project.js
  httpdocs/js/webots-cloud.js
Labels: enhancement

#43 Fix sync pagination
  httpdocs/ajax/project/create.php
  httpdocs/js/webots-cloud.js
Labels: bug

#45 Fix server page load error
  httpdocs/js/webots-cloud.js
Labels: bug

#47 Fix back button
  httpdocs/js/project.js
  httpdocs/js/router.js
  httpdocs/js/webots-cloud.js
Labels: bug
