Repository cyberbotics/webots-cloud, pull requests merged in 2022-09, with the labels that each got.

#49 Get meshes folder
  httpdocs/ajax/animation/create.php
  httpdocs/js/webots-cloud.js
Labels: bug

#52 remove www from url
  httpdocs/js/webots-cloud.js
Labels: cleanup

#50 Add a branch information
  database/webots-cloud.sql
  httpdocs/ajax/animation/create.php
  httpdocs/ajax/animation/list.php
  httpdocs/ajax/project/create.php
  httpdocs/ajax/project/list.php
  httpdocs/ajax/server/list.php
  httpdocs/ajax/server/session.php
  httpdocs/ajax/server/setup.php
  httpdocs/ajax/server/update.php
Labels: enhancement

#53 Change description
  httpdocs/index.html
Labels: documentation

#54 Update webots-cloud.js
  httpdocs/ajax/animation/create.php
  httpdocs/js/webots-cloud.js
Labels: bug

#55 Revert last commit
  httpdocs/ajax/animation/create.php
  httpdocs/js/webots-cloud.js
Labels: bug

#56 Various clean-up
  httpdocs/ajax/animation/create.php
  httpdocs/js/webots-cloud.js
Labels: cleanup

#60 Fix fork between testing and other branches
  httpdocs/js/project.js
Labels: cleanup

#63 Fix sorting
  httpdocs/css/webots-cloud.css
  httpdocs/js/webots-cloud.js
Labels: bug

#67 Fix unique url
  database/webots-cloud.sql
Labels: enhancement

#69 Benchmark: update 404.php
  httpdocs/404.php
Labels: bug
