Repository cyberbotics/webots-cloud, pull requests merged in 2022-04, with the labels that each got.

#3 Bug fixes, new synchronization, new design, code clean-up
  .eslintrc.json
  README.md
  httpdocs/ajax/project/create.php
  httpdocs/css/webots-cloud.css
  httpdocs/index.html
  httpdocs/js/modal_dialog.js
  httpdocs/js/project.js
  httpdocs/js/router.js
  httpdocs/js/webots-cloud.js
  php/animation.php
  php/github_oauth.php.template
  php/simulation.php
Labels: bug, documentation

#5 Add webots version in database for scenes, animations and simulations
  database/webots-cloud.sql
  httpdocs/ajax/animation/create.php
  httpdocs/ajax/project/create.php
  php/simulation.php
Labels: enhancement

#9 fix modal message
  httpdocs/ajax/project/create.php
Labels: bug

#11 Fix HTML injection exploit
  httpdocs/ajax/animation/list.php
  httpdocs/ajax/project/list.php
Labels: bug

#12 Hotfix PHP error
  httpdocs/ajax/animation/list.php
  httpdocs/ajax/project/list.php
Labels: bug

#15 Add security headers and merge htaccess
  httpdocs/.htaccess
  httpdocs/404.php
Labels: enhancement
