Repository cyberbotics/webots-cloud, pull requests merged in 2023-05, with the labels that each got.

#129 Add the number of views in the proto list
  httpdocs/css/webots-cloud.css
  httpdocs/images/views.png
  httpdocs/js/webots-cloud.js
Labels: enhancement

#130 Updated Terms of Service
  httpdocs/js/termsAndPrivacy.js
Labels: enhancement

#134 Fix Tiago++
  httpdocs/js/webots-cloud.js
Labels: bug

#135 Fixed English
  httpdocs/js/webots-cloud.js
Labels: cleanup

#138 Fix first level keyword display
  httpdocs/css/webots-cloud.css
  httpdocs/js/webots-cloud.js
Labels: bug
