Repository cyberbotics/webots-cloud, pull requests merged in 2023-01, with the labels that each got.

#83 Fix wrong type checking
  httpdocs/js/project.js
  php/simulation.php
Labels: cleanup

#84 Cleanup style
  httpdocs/js/project.js
  httpdocs/js/webots-cloud.js
Labels: cleanup

#85 Display evaluation queue for competitions
  httpdocs/ajax/project/queue.php
  httpdocs/js/project.js
  httpdocs/js/router.js
  httpdocs/js/termsAndPrivacy.js
  httpdocs/js/user.js
  httpdocs/js/webots-cloud.js
  httpdocs/run_competition.php
Labels: enhancement

#87 Reduce the number of calls to GitHub API
  httpdocs/js/webots-cloud.js
Labels: bug, enhancement, cleanup

#93 Testing
  httpdocs/js/project.js
Labels: enhancement

#94 Improved competition page
  httpdocs/css/webots-cloud.css
  httpdocs/js/webots-cloud.js
Labels: enhancement

#97 Fix style
  httpdocs/js/country_codes.js
  httpdocs/js/webots-cloud.js
Labels: cleanup

#98 Let to Const
  httpdocs/js/modal_dialog.js
  httpdocs/js/project.js
  httpdocs/js/router.js
  httpdocs/js/user.js
  httpdocs/js/webots-cloud.js
Labels: cleanup

#99 Add date colors and link to github users
  httpdocs/js/webots-cloud.js
Labels: enhancement
